baseurl = "/"
languageCode = "en-us"
title = "Statistical Population Genetics Reading Group"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Members"
    url = "/members/"
[[menu.main]]
    name = "Past Papers"
    url = "/past-papers/"
[[menu.main]]
    name = "Schedule"
    url = "/schedule/"
[[menu.main]]
    name = "Reading Suggestions"
    url = "/suggestions/"

[params]
    description = "Statistical Population Genetics Reading Group"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github" 

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Statistical Population Genetics"

